---
name: Bluetti to MQTT
version: 3.0.1
slug: bluetti2mqtt
description: MQTT bridge between Bluetti and Home Assistant
url: https://github.com/LzbnAndr313/bluetti2mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
usb: true
map:
  - share:rw
init: false
services:
  - mqtt:need
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_host: ""
  mqtt_port: ""
  mode: mqtt
  ha_config: normal
  bt_mac: ""
  poll_sec: 30
  scan: true
  debug: false
schema:
  mqtt_username: str?
  mqtt_password: password?
  mqtt_host: str?
  mqtt_port: port?
  mode: list(mqtt|discovery|logger)
  ha_config: list(normal|none|advanced)
  bt_mac: match(^([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2}( ([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2})*$)
  poll_sec: int
  scan: bool
  debug: bool
