---
name: Bluetti to MQTT (Beta-2)
version: 2.0.0-beta.11
breaking_versions:
  - 2.0.0-beta
slug: bluetti2mqtt-beta
description: MQTT bridge between Bluetti and Home Assistant
url: https://github.com/LzbnAndr313/bluetti2mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
usb: true
map:
  - share:rw
init: false
services:
  - mqtt:need
options:
  mqtt_username: ""
  mqtt_password: ""
  mqtt_host: ""
  mqtt_port: ""
  mode: mqtt
  ha_config: normal
  bt_mac: FE:97:60:CD:21:D4
  poll_sec: 30
  scan: false
  debug: false
schema:
  mqtt_username: str?
  mqtt_password: password?
  mqtt_host: str?
  mqtt_port: str?
  mode: list(mqtt|discovery|logger)
  ha_config: list(normal|none|advanced)
  bt_mac: match(^([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2}( ([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2})*$)
  poll_sec: int
  scan: bool
  debug: bool
